# -*- coding: utf-8 -*-
"""Explainable_Genomic_Variant_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luhbX7z8fW47ZKeggwP3nIlSlWzwCEN3
"""

!pip install xgboost shap

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, roc_auc_score, f1_score

from xgboost import XGBClassifier
import shap

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("clinvar_conflicting.csv", low_memory=False)
df = df[df["CLASS"].isin([0,1])]
df["label"] = df["CLASS"]
df.head()

df["AF_ESP"] = df["AF_ESP"].fillna(0)
df["AF_EXAC"] = df["AF_EXAC"].fillna(0)
df["AF_TGP"] = df["AF_TGP"].fillna(0)

df["maf_mean"] = df[["AF_ESP","AF_EXAC","AF_TGP"]].mean(axis=1)

epsilon = 1e-6
df["maf_log"] = -np.log10(df["maf_mean"] + epsilon)

df["radical_change"] = df["BLOSUM62"].apply(
    lambda x: 1 if pd.notnull(x) and x < 0 else 0
)

df["SIFT_score"] = df["SIFT"].str.extract(r"\((.*?)\)")
df["PolyPhen_score"] = df["PolyPhen"].str.extract(r"\((.*?)\)")

df["SIFT_score"] = pd.to_numeric(df["SIFT_score"], errors="coerce")
df["PolyPhen_score"] = pd.to_numeric(df["PolyPhen_score"], errors="coerce")

impact_encoder = LabelEncoder()
df["IMPACT_encoded"] = impact_encoder.fit_transform(df["IMPACT"].astype(str))

features = [
    "maf_log",
    "CADD_PHRED",
    "SIFT_score",
    "PolyPhen_score",
    "BLOSUM62",
    "radical_change",
    "IMPACT_encoded"
]

X = df[features]
y = df["label"]

imputer = SimpleImputer(strategy="median")
X = imputer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:,1]

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("F1 Score:", f1_score(y_test, y_pred))

importance = model.feature_importances_

feat_imp = pd.DataFrame({
    "feature": features[:X.shape[1]],
    "importance": importance
}).sort_values(by="importance", ascending=False)

feat_imp

plt.figure(figsize=(8,5))
plt.barh(feat_imp["feature"], feat_imp["importance"])
plt.gca().invert_yaxis()
plt.show()

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test, feature_names=features)



